### ISSUE TITLE
Error when Using it in combination with Ionide for Fsharp

### ISSUE THREAD

**Issue by SebastianAtWork** [oleg-shilo/codemap.vscode#89]
Hi,
I have a very weird error when using this extension in combination with ionide for Fsharp.
When loading a project I get : [09:38:54 ERROR] [LanguageService] Error starting F# language server: % [Error: Error finding dotnet version, do you have dotnet installed and on the PATH?
	at c:\Users\heads\.vscode-insiders\extensions\ionide.ionide-fsharp-7.11.0\fsharp.js:2:699849
	at c:\Users\heads\.vscode-insiders\extensions\ionide.ionide-fsharp-7.11.0\fsharp.js:2:699939
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async v.n (c:\Users\heads\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:6206)
	at async v.m (c:\Users\heads\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:6169)
	at async v.l (c:\Users\heads\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:125:5626)]
[09:38:54 ERROR] [Main] Error activating FSAC: Error: Error finding dotnet version, do you have dotnet installed and on the PATH?
[09:38:54 DEBUG] [Main] Activating features
[09:38:54 ERROR] [Main] Error loading projects: TypeError: Cannot read properties of null (reading 'Found')

I can work around that by disabling codemap, reloading window to let ionide load the projects and then enable codemap but thats a bit of a pain. Any Idea on how codemap can influence ionide for Fsharp´s startup?

**Comment by oleg-shilo** [comment]
I do not see how one extension can impact another one when locating a file on the file system. 
The only thing that both extensions have in common is that CodeMap also runs .NET launcher (dotnet.exe) in the background. But it is a different process so I do not see why F# may have any difficulties running another instance of `dotnet.exe`.

I am not sure how to help you. Since it is F# extension that throws the error, its vendor is in a much better position to assist you. They can easily repeat your test and see under the debugger why the extension spits the dummy.
I suggest you contact "ionide for Fsharp" vendor
